<?php

use Illuminate\Database\Seeder;
use App\MstKabupaten;
use Carbon\Carbon;

class KabupatenTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $kabupatens = [
            ['kd_kabupaten'  => '1101','kd_provinsi'   => '11','kabupaten'     => 'SIMEULUE','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1102','kd_provinsi'   => '11','kabupaten'     => 'ACEH SINGKIL','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1103','kd_provinsi'   => '11','kabupaten'     => 'ACEH SELATAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1104','kd_provinsi'   => '11','kabupaten'     => 'ACEH TENGGARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1105','kd_provinsi'   => '11','kabupaten'     => 'ACEH TIMUR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1106','kd_provinsi'   => '11','kabupaten'     => 'ACEH TENGAH','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1107','kd_provinsi'   => '11','kabupaten'     => 'ACEH BARAT','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1108','kd_provinsi'   => '11','kabupaten'     => 'ACEH BESAR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1109','kd_provinsi'   => '11','kabupaten'     => 'PIDIE','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1110','kd_provinsi'   => '11','kabupaten'     => 'BIREUEN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1111','kd_provinsi'   => '11','kabupaten'     => 'ACEH UTARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1112','kd_provinsi'   => '11','kabupaten'     => 'ACEH BARAT DAYA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1113','kd_provinsi'   => '11','kabupaten'     => 'GAYO LUES','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1114','kd_provinsi'   => '11','kabupaten'     => 'ACEH TAMIANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1115','kd_provinsi'   => '11','kabupaten'     => 'NAGAN RAYA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1116','kd_provinsi'   => '11','kabupaten'     => 'ACEH JAYA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1117','kd_provinsi'   => '11','kabupaten'     => 'BENER MERIAH','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1118','kd_provinsi'   => '11','kabupaten'     => 'PIDIE JAYA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1171','kd_provinsi'   => '11','kabupaten'     => 'KOTA BANDA ACEH','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1172','kd_provinsi'   => '11','kabupaten'     => 'KOTA SABANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1173','kd_provinsi'   => '11','kabupaten'     => 'KOTA LANGSA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1174','kd_provinsi'   => '11','kabupaten'     => 'KOTA LHOKSEUMAWE','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1175','kd_provinsi'   => '11','kabupaten'     => 'KOTA SUBULUSSALAM','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1201','kd_provinsi'   => '12','kabupaten'     => 'NIAS','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1202','kd_provinsi'   => '12','kabupaten'     => 'MANDAILING NATAL','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1203','kd_provinsi'   => '12','kabupaten'     => 'TAPANULI SELATAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1204','kd_provinsi'   => '12','kabupaten'     => 'TAPANULI TENGAH','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1205','kd_provinsi'   => '12','kabupaten'     => 'TAPANULI UTARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1206','kd_provinsi'   => '12','kabupaten'     => 'TOBA SAMOSIR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1207','kd_provinsi'   => '12','kabupaten'     => 'LABUHAN BATU','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1208','kd_provinsi'   => '12','kabupaten'     => 'ASAHAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1209','kd_provinsi'   => '12','kabupaten'     => 'SIMALUNGUN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1210','kd_provinsi'   => '12','kabupaten'     => 'DAIRI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1211','kd_provinsi'   => '12','kabupaten'     => 'KARO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1212','kd_provinsi'   => '12','kabupaten'     => 'DELI SERDANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1213','kd_provinsi'   => '12','kabupaten'     => 'LANGKAT','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1214','kd_provinsi'   => '12','kabupaten'     => 'NIAS SELATAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1215','kd_provinsi'   => '12','kabupaten'     => 'HUMBANG HASUNDUTAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1216','kd_provinsi'   => '12','kabupaten'     => 'PAKPAK BHARAT','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1217','kd_provinsi'   => '12','kabupaten'     => 'SAMOSIR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1218','kd_provinsi'   => '12','kabupaten'     => 'SERDANG BEDAGAI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1219','kd_provinsi'   => '12','kabupaten'     => 'BATU BARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1220','kd_provinsi'   => '12','kabupaten'     => 'PADANG LAWAS UTARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1221','kd_provinsi'   => '12','kabupaten'     => 'PADANG LAWAS','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1222','kd_provinsi'   => '12','kabupaten'     => 'LABUHAN BATU SELATAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1223','kd_provinsi'   => '12','kabupaten'     => 'LABUHAN BATU UTARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1224','kd_provinsi'   => '12','kabupaten'     => 'NIAS UTARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1225','kd_provinsi'   => '12','kabupaten'     => 'NIAS BARAT','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1271','kd_provinsi'   => '12','kabupaten'     => 'KOTA SIBOLGA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1272','kd_provinsi'   => '12','kabupaten'     => 'KOTA TANJUNG BALAI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1273','kd_provinsi'   => '12','kabupaten'     => 'KOTA PEMATANG SIANTAR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1274','kd_provinsi'   => '12','kabupaten'     => 'KOTA TEBING TINGGI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1275','kd_provinsi'   => '12','kabupaten'     => 'KOTA MEDAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1276','kd_provinsi'   => '12','kabupaten'     => 'KOTA BINJAI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1277','kd_provinsi'   => '12','kabupaten'     => 'KOTA PADANGSIDIMPUAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1278','kd_provinsi'   => '12','kabupaten'     => 'KOTA GUNUNGSITOLI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1301','kd_provinsi'   => '13','kabupaten'     => 'KEPULAUAN MENTAWAI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1302','kd_provinsi'   => '13','kabupaten'     => 'PESISIR SELATAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1303','kd_provinsi'   => '13','kabupaten'     => 'SOLOK','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1304','kd_provinsi'   => '13','kabupaten'     => 'SIJUNJUNG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1305','kd_provinsi'   => '13','kabupaten'     => 'TANAH DATAR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1306','kd_provinsi'   => '13','kabupaten'     => 'PADANG PARIAMAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1307','kd_provinsi'   => '13','kabupaten'     => 'AGAM','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1308','kd_provinsi'   => '13','kabupaten'     => 'LIMA PULUH KOTA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1309','kd_provinsi'   => '13','kabupaten'     => 'PASAMAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1310','kd_provinsi'   => '13','kabupaten'     => 'SOLOK SELATAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1311','kd_provinsi'   => '13','kabupaten'     => 'DHARMAS RAYA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1312','kd_provinsi'   => '13','kabupaten'     => 'PASAMAN BARAT','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1371','kd_provinsi'   => '13','kabupaten'     => 'KOTA PADANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1372','kd_provinsi'   => '13','kabupaten'     => 'KOTA SOLOK','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1373','kd_provinsi'   => '13','kabupaten'     => 'KOTA SAWAH LUNTO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1374','kd_provinsi'   => '13','kabupaten'     => 'KOTA PADANG PANJANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1375','kd_provinsi'   => '13','kabupaten'     => 'KOTA BUKITTINGGI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1376','kd_provinsi'   => '13','kabupaten'     => 'KOTA PAYAKUMBUH','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1377','kd_provinsi'   => '13','kabupaten'     => 'KOTA PARIAMAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1401','kd_provinsi'   => '14','kabupaten'     => 'KUANTAN SINGINGI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1402','kd_provinsi'   => '14','kabupaten'     => 'INDRAGIRI HULU','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1403','kd_provinsi'   => '14','kabupaten'     => 'INDRAGIRI HILIR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1404','kd_provinsi'   => '14','kabupaten'     => 'PELALAWAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1405','kd_provinsi'   => '14','kabupaten'     => 'SIAK','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1406','kd_provinsi'   => '14','kabupaten'     => 'KAMPAR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1407','kd_provinsi'   => '14','kabupaten'     => 'ROKAN HULU','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1408','kd_provinsi'   => '14','kabupaten'     => 'BENGKALIS','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1409','kd_provinsi'   => '14','kabupaten'     => 'ROKAN HILIR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1410','kd_provinsi'   => '14','kabupaten'     => 'KEPULAUAN MERANTI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1471','kd_provinsi'   => '14','kabupaten'     => 'KOTA PEKANBARU','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1473','kd_provinsi'   => '14','kabupaten'     => 'KOTA DUMAI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1501','kd_provinsi'   => '15','kabupaten'     => 'KERINCI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1502','kd_provinsi'   => '15','kabupaten'     => 'MERANGIN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1503','kd_provinsi'   => '15','kabupaten'     => 'SAROLANGUN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1504','kd_provinsi'   => '15','kabupaten'     => 'BATANG HARI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1505','kd_provinsi'   => '15','kabupaten'     => 'MUARO JAMBI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1506','kd_provinsi'   => '15','kabupaten'     => 'TANJUNG JABUNG TIMUR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1507','kd_provinsi'   => '15','kabupaten'     => 'TANJUNG JABUNG BARAT','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1508','kd_provinsi'   => '15','kabupaten'     => 'TEBO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1509','kd_provinsi'   => '15','kabupaten'     => 'BUNGO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1571','kd_provinsi'   => '15','kabupaten'     => 'KOTA JAMBI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1572','kd_provinsi'   => '15','kabupaten'     => 'KOTA SUNGAI PENUH','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1601','kd_provinsi'   => '16','kabupaten'     => 'OGAN KOMERING ULU','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1602','kd_provinsi'   => '16','kabupaten'     => 'OGAN KOMERING ILIR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1603','kd_provinsi'   => '16','kabupaten'     => 'MUARA ENIM','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1604','kd_provinsi'   => '16','kabupaten'     => 'LAHAT','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1605','kd_provinsi'   => '16','kabupaten'     => 'MUSI RAWAS','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1606','kd_provinsi'   => '16','kabupaten'     => 'MUSI BANYUASIN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1607','kd_provinsi'   => '16','kabupaten'     => 'BANYU ASIN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1608','kd_provinsi'   => '16','kabupaten'     => 'OGAN KOMERING ULU SELATAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1609','kd_provinsi'   => '16','kabupaten'     => 'OGAN KOMERING ULU TIMUR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1610','kd_provinsi'   => '16','kabupaten'     => 'OGAN ILIR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1611','kd_provinsi'   => '16','kabupaten'     => 'EMPAT LAWANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1671','kd_provinsi'   => '16','kabupaten'     => 'KOTA PALEMBANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1672','kd_provinsi'   => '16','kabupaten'     => 'KOTA PRABUMULIH','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1673','kd_provinsi'   => '16','kabupaten'     => 'KOTA PAGAR ALAM','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1674','kd_provinsi'   => '16','kabupaten'     => 'KOTA LUBUKLINGGAU','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1701','kd_provinsi'   => '17','kabupaten'     => 'BENGKULU SELATAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1702','kd_provinsi'   => '17','kabupaten'     => 'REJANG LEBONG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1703','kd_provinsi'   => '17','kabupaten'     => 'BENGKULU UTARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1704','kd_provinsi'   => '17','kabupaten'     => 'KAUR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1705','kd_provinsi'   => '17','kabupaten'     => 'SELUMA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1706','kd_provinsi'   => '17','kabupaten'     => 'MUKOMUKO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1707','kd_provinsi'   => '17','kabupaten'     => 'LEBONG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1708','kd_provinsi'   => '17','kabupaten'     => 'KEPAHIANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1709','kd_provinsi'   => '17','kabupaten'     => 'BENGKULU TENGAH','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1771','kd_provinsi'   => '17','kabupaten'     => 'KOTA BENGKULU','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1801','kd_provinsi'   => '18','kabupaten'     => 'LAMPUNG BARAT','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1802','kd_provinsi'   => '18','kabupaten'     => 'TANGGAMUS','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1803','kd_provinsi'   => '18','kabupaten'     => 'LAMPUNG SELATAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1804','kd_provinsi'   => '18','kabupaten'     => 'LAMPUNG TIMUR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1805','kd_provinsi'   => '18','kabupaten'     => 'LAMPUNG TENGAH','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1806','kd_provinsi'   => '18','kabupaten'     => 'LAMPUNG UTARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1807','kd_provinsi'   => '18','kabupaten'     => 'WAY KANAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1808','kd_provinsi'   => '18','kabupaten'     => 'TULANGBAWANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1809','kd_provinsi'   => '18','kabupaten'     => 'PESAWARAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1810','kd_provinsi'   => '18','kabupaten'     => 'PRINGSEWU','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1811','kd_provinsi'   => '18','kabupaten'     => 'MESUJI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1812','kd_provinsi'   => '18','kabupaten'     => 'TULANGBAWANG BARAT','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1871','kd_provinsi'   => '18','kabupaten'     => 'KOTA BANDAR LAMPUNG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1872','kd_provinsi'   => '18','kabupaten'     => 'KOTA METRO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1901','kd_provinsi'   => '19','kabupaten'     => 'BANGKA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1902','kd_provinsi'   => '19','kabupaten'     => 'BELITUNG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1903','kd_provinsi'   => '19','kabupaten'     => 'BANGKA BARAT','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1904','kd_provinsi'   => '19','kabupaten'     => 'BANGKA TENGAH','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1905','kd_provinsi'   => '19','kabupaten'     => 'BANGKA SELATAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1906','kd_provinsi'   => '19','kabupaten'     => 'BELITUNG TIMUR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '1971','kd_provinsi'   => '19','kabupaten'     => 'KOTA PANGKAL PINANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '2101','kd_provinsi'   => '21','kabupaten'     => 'KARIMUN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '2102','kd_provinsi'   => '21','kabupaten'     => 'BINTAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '2103','kd_provinsi'   => '21','kabupaten'     => 'NATUNA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '2104','kd_provinsi'   => '21','kabupaten'     => 'LINGGA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '2105','kd_provinsi'   => '21','kabupaten'     => 'KEPULAUAN ANAMBAS','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '2171','kd_provinsi'   => '21','kabupaten'     => 'KOTA BATAM','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '2172','kd_provinsi'   => '21','kabupaten'     => 'KOTA TANJUNG PINANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3101','kd_provinsi'   => '31','kabupaten'     => 'KEPULAUAN SERIBU','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3171','kd_provinsi'   => '31','kabupaten'     => 'KODYA JAKARTA SELATAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3172','kd_provinsi'   => '31','kabupaten'     => 'KODYA JAKARTA TIMUR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3173','kd_provinsi'   => '31','kabupaten'     => 'KODYA JAKARTA PUSAT','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3174','kd_provinsi'   => '31','kabupaten'     => 'KODYA JAKARTA BARAT','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3175','kd_provinsi'   => '31','kabupaten'     => 'KODYA JAKARTA UTARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3201','kd_provinsi'   => '32','kabupaten'     => 'BOGOR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3202','kd_provinsi'   => '32','kabupaten'     => 'SUKABUMI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3203','kd_provinsi'   => '32','kabupaten'     => 'CIANJUR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3204','kd_provinsi'   => '32','kabupaten'     => 'BANDUNG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3205','kd_provinsi'   => '32','kabupaten'     => 'GARUT','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3206','kd_provinsi'   => '32','kabupaten'     => 'TASIKMALAYA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3207','kd_provinsi'   => '32','kabupaten'     => 'CIAMIS','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3208','kd_provinsi'   => '32','kabupaten'     => 'KUNINGAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3209','kd_provinsi'   => '32','kabupaten'     => 'CIREBON','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3210','kd_provinsi'   => '32','kabupaten'     => 'MAJALENGKA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3211','kd_provinsi'   => '32','kabupaten'     => 'SUMEDANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3212','kd_provinsi'   => '32','kabupaten'     => 'INDRAMAYU','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3213','kd_provinsi'   => '32','kabupaten'     => 'SUBANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3214','kd_provinsi'   => '32','kabupaten'     => 'PURWAKARTA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3215','kd_provinsi'   => '32','kabupaten'     => 'KARAWANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3216','kd_provinsi'   => '32','kabupaten'     => 'BEKASI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3217','kd_provinsi'   => '32','kabupaten'     => 'BANDUNG BARAT','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3271','kd_provinsi'   => '32','kabupaten'     => 'KOTA BOGOR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3272','kd_provinsi'   => '32','kabupaten'     => 'KOTA SUKABUMI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3273','kd_provinsi'   => '32','kabupaten'     => 'KOTA BANDUNG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3274','kd_provinsi'   => '32','kabupaten'     => 'KOTA CIREBON','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3275','kd_provinsi'   => '32','kabupaten'     => 'KOTA BEKASI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3276','kd_provinsi'   => '32','kabupaten'     => 'KOTA DEPOK','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3277','kd_provinsi'   => '32','kabupaten'     => 'KOTA CIMAHI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3278','kd_provinsi'   => '32','kabupaten'     => 'KOTA TASIKMALAYA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3279','kd_provinsi'   => '32','kabupaten'     => 'KOTA BANJAR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3301','kd_provinsi'   => '33','kabupaten'     => 'CILACAP','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3302','kd_provinsi'   => '33','kabupaten'     => 'BANYUMAS','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3303','kd_provinsi'   => '33','kabupaten'     => 'PURBALINGGA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3304','kd_provinsi'   => '33','kabupaten'     => 'BANJARNEGARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3305','kd_provinsi'   => '33','kabupaten'     => 'KEBUMEN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3306','kd_provinsi'   => '33','kabupaten'     => 'PURWOREJO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3307','kd_provinsi'   => '33','kabupaten'     => 'WONOSOBO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3308','kd_provinsi'   => '33','kabupaten'     => 'MAGELANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3309','kd_provinsi'   => '33','kabupaten'     => 'BOYOLALI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3310','kd_provinsi'   => '33','kabupaten'     => 'KLATEN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3311','kd_provinsi'   => '33','kabupaten'     => 'SUKOHARJO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3312','kd_provinsi'   => '33','kabupaten'     => 'WONOGIRI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3313','kd_provinsi'   => '33','kabupaten'     => 'KARANGANYAR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3314','kd_provinsi'   => '33','kabupaten'     => 'SRAGEN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3315','kd_provinsi'   => '33','kabupaten'     => 'GROBOGAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3316','kd_provinsi'   => '33','kabupaten'     => 'BLORA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3317','kd_provinsi'   => '33','kabupaten'     => 'REMBANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3318','kd_provinsi'   => '33','kabupaten'     => 'PATI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3319','kd_provinsi'   => '33','kabupaten'     => 'KUDUS','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3320','kd_provinsi'   => '33','kabupaten'     => 'JEPARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3321','kd_provinsi'   => '33','kabupaten'     => 'DEMAK','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3322','kd_provinsi'   => '33','kabupaten'     => 'SEMARANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3323','kd_provinsi'   => '33','kabupaten'     => 'TEMANGGUNG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3324','kd_provinsi'   => '33','kabupaten'     => 'KENDAL','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3325','kd_provinsi'   => '33','kabupaten'     => 'BATANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3326','kd_provinsi'   => '33','kabupaten'     => 'PEKALONGAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3327','kd_provinsi'   => '33','kabupaten'     => 'PEMALANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3328','kd_provinsi'   => '33','kabupaten'     => 'TEGAL','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3329','kd_provinsi'   => '33','kabupaten'     => 'BREBES','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3371','kd_provinsi'   => '33','kabupaten'     => 'KOTA MAGELANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3372','kd_provinsi'   => '33','kabupaten'     => 'KOTA SURAKARTA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3373','kd_provinsi'   => '33','kabupaten'     => 'KOTA SALATIGA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3374','kd_provinsi'   => '33','kabupaten'     => 'KOTA SEMARANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3375','kd_provinsi'   => '33','kabupaten'     => 'KOTA PEKALONGAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3376','kd_provinsi'   => '33','kabupaten'     => 'KOTA TEGAL','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3401','kd_provinsi'   => '34','kabupaten'     => 'KULON PROGO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3402','kd_provinsi'   => '34','kabupaten'     => 'BANTUL','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3403','kd_provinsi'   => '34','kabupaten'     => 'GUNUNG KIDUL','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3404','kd_provinsi'   => '34','kabupaten'     => 'SLEMAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3471','kd_provinsi'   => '34','kabupaten'     => 'KOTA YOGYAKARTA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3501','kd_provinsi'   => '35','kabupaten'     => 'PACITAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3502','kd_provinsi'   => '35','kabupaten'     => 'PONOROGO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3503','kd_provinsi'   => '35','kabupaten'     => 'TRENGGALEK','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3504','kd_provinsi'   => '35','kabupaten'     => 'TULUNGAGUNG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3505','kd_provinsi'   => '35','kabupaten'     => 'BLITAR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3506','kd_provinsi'   => '35','kabupaten'     => 'KEDIRI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3507','kd_provinsi'   => '35','kabupaten'     => 'MALANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3508','kd_provinsi'   => '35','kabupaten'     => 'LUMAJANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3509','kd_provinsi'   => '35','kabupaten'     => 'JEMBER','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3510','kd_provinsi'   => '35','kabupaten'     => 'BANYUWANGI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3511','kd_provinsi'   => '35','kabupaten'     => 'BONDOWOSO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3512','kd_provinsi'   => '35','kabupaten'     => 'SITUBONDO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3513','kd_provinsi'   => '35','kabupaten'     => 'PROBOLINGGO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3514','kd_provinsi'   => '35','kabupaten'     => 'PASURUAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3515','kd_provinsi'   => '35','kabupaten'     => 'SIDOARJO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3516','kd_provinsi'   => '35','kabupaten'     => 'MOJOKERTO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3517','kd_provinsi'   => '35','kabupaten'     => 'JOMBANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3518','kd_provinsi'   => '35','kabupaten'     => 'NGANJUK','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3519','kd_provinsi'   => '35','kabupaten'     => 'MADIUN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3520','kd_provinsi'   => '35','kabupaten'     => 'MAGETAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3521','kd_provinsi'   => '35','kabupaten'     => 'NGAWI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3522','kd_provinsi'   => '35','kabupaten'     => 'BOJONEGORO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3523','kd_provinsi'   => '35','kabupaten'     => 'TUBAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3524','kd_provinsi'   => '35','kabupaten'     => 'LAMONGAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3525','kd_provinsi'   => '35','kabupaten'     => 'GRESIK','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3526','kd_provinsi'   => '35','kabupaten'     => 'BANGKALAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3527','kd_provinsi'   => '35','kabupaten'     => 'SAMPANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3528','kd_provinsi'   => '35','kabupaten'     => 'PAMEKASAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3529','kd_provinsi'   => '35','kabupaten'     => 'SUMENEP','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3571','kd_provinsi'   => '35','kabupaten'     => 'KOTA KEDIRI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3572','kd_provinsi'   => '35','kabupaten'     => 'KOTA BLITAR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3573','kd_provinsi'   => '35','kabupaten'     => 'KOTA MALANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3574','kd_provinsi'   => '35','kabupaten'     => 'KOTA PROBOLINGGO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3575','kd_provinsi'   => '35','kabupaten'     => 'KOTA PASURUAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3576','kd_provinsi'   => '35','kabupaten'     => 'KOTA MOJOKERTO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3577','kd_provinsi'   => '35','kabupaten'     => 'KOTA MADIUN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3578','kd_provinsi'   => '35','kabupaten'     => 'KOTA SURABAYA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3579','kd_provinsi'   => '35','kabupaten'     => 'KOTA BATU','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3601','kd_provinsi'   => '36','kabupaten'     => 'PANDEGLANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3602','kd_provinsi'   => '36','kabupaten'     => 'LEBAK','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3603','kd_provinsi'   => '36','kabupaten'     => 'TANGERANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3604','kd_provinsi'   => '36','kabupaten'     => 'SERANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3671','kd_provinsi'   => '36','kabupaten'     => 'KOTA TANGERANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3672','kd_provinsi'   => '36','kabupaten'     => 'KOTA CILEGON','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3673','kd_provinsi'   => '36','kabupaten'     => 'KOTA SERANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '3674','kd_provinsi'   => '36','kabupaten'     => 'KOTA TANGERANG SELATAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5101','kd_provinsi'   => '51','kabupaten'     => 'JEMBRANA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5102','kd_provinsi'   => '51','kabupaten'     => 'TABANAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5103','kd_provinsi'   => '51','kabupaten'     => 'BADUNG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5104','kd_provinsi'   => '51','kabupaten'     => 'GIANYAR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5105','kd_provinsi'   => '51','kabupaten'     => 'KLUNGKUNG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5106','kd_provinsi'   => '51','kabupaten'     => 'BANGLI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5107','kd_provinsi'   => '51','kabupaten'     => 'KARANG ASEM','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5108','kd_provinsi'   => '51','kabupaten'     => 'BULELENG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5171','kd_provinsi'   => '51','kabupaten'     => 'KOTA DENPASAR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5201','kd_provinsi'   => '52','kabupaten'     => 'LOMBOK BARAT','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5202','kd_provinsi'   => '52','kabupaten'     => 'LOMBOK TENGAH','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5203','kd_provinsi'   => '52','kabupaten'     => 'LOMBOK TIMUR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5204','kd_provinsi'   => '52','kabupaten'     => 'SUMBAWA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5205','kd_provinsi'   => '52','kabupaten'     => 'DOMPU','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5206','kd_provinsi'   => '52','kabupaten'     => 'BIMA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5207','kd_provinsi'   => '52','kabupaten'     => 'SUMBAWA BARAT','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5208','kd_provinsi'   => '52','kabupaten'     => 'LOMBOK UTARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5271','kd_provinsi'   => '52','kabupaten'     => 'KOTA MATARAM','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5272','kd_provinsi'   => '52','kabupaten'     => 'KOTA BIMA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5301','kd_provinsi'   => '53','kabupaten'     => 'SUMBA BARAT','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5302','kd_provinsi'   => '53','kabupaten'     => 'SUMBA TIMUR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5303','kd_provinsi'   => '53','kabupaten'     => 'KUPANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5304','kd_provinsi'   => '53','kabupaten'     => 'TIMOR TENGAH SELATAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5305','kd_provinsi'   => '53','kabupaten'     => 'TIMOR TENGAH UTARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5306','kd_provinsi'   => '53','kabupaten'     => 'BELU','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5307','kd_provinsi'   => '53','kabupaten'     => 'ALOR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5308','kd_provinsi'   => '53','kabupaten'     => 'LEMBATA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5309','kd_provinsi'   => '53','kabupaten'     => 'FLORES TIMUR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5310','kd_provinsi'   => '53','kabupaten'     => 'SIKKA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5311','kd_provinsi'   => '53','kabupaten'     => 'ENDE','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5312','kd_provinsi'   => '53','kabupaten'     => 'NGADA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5313','kd_provinsi'   => '53','kabupaten'     => 'MANGGARAI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5314','kd_provinsi'   => '53','kabupaten'     => 'ROTE NDAO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5315','kd_provinsi'   => '53','kabupaten'     => 'MANGGARAI BARAT','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5316','kd_provinsi'   => '53','kabupaten'     => 'SUMBA TENGAH','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5317','kd_provinsi'   => '53','kabupaten'     => 'SUMBA BARAT DAYA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5318','kd_provinsi'   => '53','kabupaten'     => 'NAGEKEO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5319','kd_provinsi'   => '53','kabupaten'     => 'MANGGARAI TIMUR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5320','kd_provinsi'   => '53','kabupaten'     => 'SABU RAIJUA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '5371','kd_provinsi'   => '53','kabupaten'     => 'KOTA KUPANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6101','kd_provinsi'   => '61','kabupaten'     => 'SAMBAS','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6102','kd_provinsi'   => '61','kabupaten'     => 'BENGKAYANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6103','kd_provinsi'   => '61','kabupaten'     => 'LANDAK','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6104','kd_provinsi'   => '61','kabupaten'     => 'PONTIANAK','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6105','kd_provinsi'   => '61','kabupaten'     => 'SANGGAU','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6106','kd_provinsi'   => '61','kabupaten'     => 'KETAPANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6107','kd_provinsi'   => '61','kabupaten'     => 'SINTANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6108','kd_provinsi'   => '61','kabupaten'     => 'KAPUAS HULU','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6109','kd_provinsi'   => '61','kabupaten'     => 'SEKADAU','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6110','kd_provinsi'   => '61','kabupaten'     => 'MELAWI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6111','kd_provinsi'   => '61','kabupaten'     => 'KAYONG UTARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6112','kd_provinsi'   => '61','kabupaten'     => 'KUBU RAYA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6171','kd_provinsi'   => '61','kabupaten'     => 'KOTA PONTIANAK','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6172','kd_provinsi'   => '61','kabupaten'     => 'KOTA SINGKAWANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6201','kd_provinsi'   => '62','kabupaten'     => 'KOTAWARINGIN BARAT','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6202','kd_provinsi'   => '62','kabupaten'     => 'KOTAWARINGIN TIMUR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6203','kd_provinsi'   => '62','kabupaten'     => 'KAPUAS','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6204','kd_provinsi'   => '62','kabupaten'     => 'BARITO SELATAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6205','kd_provinsi'   => '62','kabupaten'     => 'BARITO UTARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6206','kd_provinsi'   => '62','kabupaten'     => 'SUKAMARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6207','kd_provinsi'   => '62','kabupaten'     => 'LAMANDAU','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6208','kd_provinsi'   => '62','kabupaten'     => 'SERUYAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6209','kd_provinsi'   => '62','kabupaten'     => 'KATINGAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6210','kd_provinsi'   => '62','kabupaten'     => 'PULANG PISAU','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6211','kd_provinsi'   => '62','kabupaten'     => 'GUNUNG MAS','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6212','kd_provinsi'   => '62','kabupaten'     => 'BARITO TIMUR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6213','kd_provinsi'   => '62','kabupaten'     => 'MURUNG RAYA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6271','kd_provinsi'   => '62','kabupaten'     => 'KOTA PALANGKA RAYA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6301','kd_provinsi'   => '63','kabupaten'     => 'TANAH LAUT','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6302','kd_provinsi'   => '63','kabupaten'     => 'KOTA BARU','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6303','kd_provinsi'   => '63','kabupaten'     => 'BANJAR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6304','kd_provinsi'   => '63','kabupaten'     => 'BARITO KUALA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6305','kd_provinsi'   => '63','kabupaten'     => 'TAPIN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6306','kd_provinsi'   => '63','kabupaten'     => 'HULU SUNGAI SELATAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6307','kd_provinsi'   => '63','kabupaten'     => 'HULU SUNGAI TENGAH','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6308','kd_provinsi'   => '63','kabupaten'     => 'HULU SUNGAI UTARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6309','kd_provinsi'   => '63','kabupaten'     => 'TABALONG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6310','kd_provinsi'   => '63','kabupaten'     => 'TANAH BUMBU','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6311','kd_provinsi'   => '63','kabupaten'     => 'BALANGAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6371','kd_provinsi'   => '63','kabupaten'     => 'KOTA BANJARMASIN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6372','kd_provinsi'   => '63','kabupaten'     => 'KOTA BANJAR BARU','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6401','kd_provinsi'   => '64','kabupaten'     => 'PASIR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6402','kd_provinsi'   => '64','kabupaten'     => 'KUTAI BARAT','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6403','kd_provinsi'   => '64','kabupaten'     => 'KUTAI KARTANEGARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6404','kd_provinsi'   => '64','kabupaten'     => 'KUTAI TIMUR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6405','kd_provinsi'   => '64','kabupaten'     => 'BERAU','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6406','kd_provinsi'   => '64','kabupaten'     => 'MALINAU','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6407','kd_provinsi'   => '64','kabupaten'     => 'BULUNGAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6408','kd_provinsi'   => '64','kabupaten'     => 'NUNUKAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6409','kd_provinsi'   => '64','kabupaten'     => 'PENAJAM PASER UTARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6410','kd_provinsi'   => '64','kabupaten'     => 'TANA TIDUNG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6471','kd_provinsi'   => '64','kabupaten'     => 'KOTA BALIKPAPAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6472','kd_provinsi'   => '64','kabupaten'     => 'KOTA SAMARINDA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6473','kd_provinsi'   => '64','kabupaten'     => 'KOTA TARAKAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '6474','kd_provinsi'   => '64','kabupaten'     => 'KOTA BONTANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7101','kd_provinsi'   => '71','kabupaten'     => 'BOLAANG MONGONDOW','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7102','kd_provinsi'   => '71','kabupaten'     => 'MINAHASA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7103','kd_provinsi'   => '71','kabupaten'     => 'KEPULAUAN SANGIHE','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7104','kd_provinsi'   => '71','kabupaten'     => 'KEPULAUAN TALAUD','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7105','kd_provinsi'   => '71','kabupaten'     => 'MINAHASA SELATAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7106','kd_provinsi'   => '71','kabupaten'     => 'MINAHASA UTARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7107','kd_provinsi'   => '71','kabupaten'     => 'BOLAANG MONGONDOW UTARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7108','kd_provinsi'   => '71','kabupaten'     => 'SIAU TAGULANDANG BIARO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7109','kd_provinsi'   => '71','kabupaten'     => 'MINAHASA TENGGARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7110','kd_provinsi'   => '71','kabupaten'     => 'BOLAANG MONGONDOW SELATAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7111','kd_provinsi'   => '71','kabupaten'     => 'BOLAANG MONGONDOW TIMUR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7171','kd_provinsi'   => '71','kabupaten'     => 'KOTA MANADO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7172','kd_provinsi'   => '71','kabupaten'     => 'KOTA BITUNG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7173','kd_provinsi'   => '71','kabupaten'     => 'KOTA TOMOHON','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7174','kd_provinsi'   => '71','kabupaten'     => 'KOTA KOTAMOBAGU','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7201','kd_provinsi'   => '72','kabupaten'     => 'BANGGAI KEPULAUAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7202','kd_provinsi'   => '72','kabupaten'     => 'BANGGAI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7203','kd_provinsi'   => '72','kabupaten'     => 'MOROWALI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7204','kd_provinsi'   => '72','kabupaten'     => 'POSO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7205','kd_provinsi'   => '72','kabupaten'     => 'DONGGALA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7206','kd_provinsi'   => '72','kabupaten'     => 'TOLI-TOLI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7207','kd_provinsi'   => '72','kabupaten'     => 'BUOL','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7208','kd_provinsi'   => '72','kabupaten'     => 'PARIGI MOUTONG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7209','kd_provinsi'   => '72','kabupaten'     => 'TOJO UNA-UNA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7210','kd_provinsi'   => '72','kabupaten'     => 'SIGI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7271','kd_provinsi'   => '72','kabupaten'     => 'KOTA PALU','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7301','kd_provinsi'   => '73','kabupaten'     => 'KEPULAUAN SELAYAR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7302','kd_provinsi'   => '73','kabupaten'     => 'BULUKUMBA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7303','kd_provinsi'   => '73','kabupaten'     => 'BANTAENG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7304','kd_provinsi'   => '73','kabupaten'     => 'JENEPONTO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7305','kd_provinsi'   => '73','kabupaten'     => 'TAKALAR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7306','kd_provinsi'   => '73','kabupaten'     => 'GOWA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7307','kd_provinsi'   => '73','kabupaten'     => 'SINJAI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7308','kd_provinsi'   => '73','kabupaten'     => 'MAROS','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7309','kd_provinsi'   => '73','kabupaten'     => 'PANGKAJENE DAN KEPULAUAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7310','kd_provinsi'   => '73','kabupaten'     => 'BARRU','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7311','kd_provinsi'   => '73','kabupaten'     => 'BONE','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7312','kd_provinsi'   => '73','kabupaten'     => 'SOPPENG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7313','kd_provinsi'   => '73','kabupaten'     => 'WAJO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7314','kd_provinsi'   => '73','kabupaten'     => 'SIDENRENG RAPPANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7315','kd_provinsi'   => '73','kabupaten'     => 'PINRANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7316','kd_provinsi'   => '73','kabupaten'     => 'ENREKANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7317','kd_provinsi'   => '73','kabupaten'     => 'LUWU','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7318','kd_provinsi'   => '73','kabupaten'     => 'TANA TORAJA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7322','kd_provinsi'   => '73','kabupaten'     => 'LUWU UTARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7325','kd_provinsi'   => '73','kabupaten'     => 'LUWU TIMUR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7326','kd_provinsi'   => '73','kabupaten'     => 'TORAJA UTARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7371','kd_provinsi'   => '73','kabupaten'     => 'KOTA MAKASSAR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7372','kd_provinsi'   => '73','kabupaten'     => 'KOTA PARE-PARE','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7373','kd_provinsi'   => '73','kabupaten'     => 'KOTA PALOPO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7401','kd_provinsi'   => '74','kabupaten'     => 'BUTON','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7402','kd_provinsi'   => '74','kabupaten'     => 'MUNA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7403','kd_provinsi'   => '74','kabupaten'     => 'KONAWE','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7404','kd_provinsi'   => '74','kabupaten'     => 'KOLAKA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7405','kd_provinsi'   => '74','kabupaten'     => 'KONAWE SELATAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7406','kd_provinsi'   => '74','kabupaten'     => 'BOMBANA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7407','kd_provinsi'   => '74','kabupaten'     => 'WAKATOBI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7408','kd_provinsi'   => '74','kabupaten'     => 'KOLAKA UTARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7409','kd_provinsi'   => '74','kabupaten'     => 'BUTON UTARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7410','kd_provinsi'   => '74','kabupaten'     => 'KONAWE UTARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7471','kd_provinsi'   => '74','kabupaten'     => 'KOTA KENDARI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7472','kd_provinsi'   => '74','kabupaten'     => 'KOTA BAU-BAU','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7501','kd_provinsi'   => '75','kabupaten'     => 'BOALEMO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7502','kd_provinsi'   => '75','kabupaten'     => 'GORONTALO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7503','kd_provinsi'   => '75','kabupaten'     => 'POHUWATO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7504','kd_provinsi'   => '75','kabupaten'     => 'BONE BOLANGO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7505','kd_provinsi'   => '75','kabupaten'     => 'GORONTALO UTARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7571','kd_provinsi'   => '75','kabupaten'     => 'KOTA GORONTALO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7601','kd_provinsi'   => '76','kabupaten'     => 'MAJENE','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7602','kd_provinsi'   => '76','kabupaten'     => 'POLEWALI MANDAR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7603','kd_provinsi'   => '76','kabupaten'     => 'MAMASA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7604','kd_provinsi'   => '76','kabupaten'     => 'MAMUJU','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '7605','kd_provinsi'   => '76','kabupaten'     => 'MAMUJU UTARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '8101','kd_provinsi'   => '81','kabupaten'     => 'MALUKU TENGGARA BARAT','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '8102','kd_provinsi'   => '81','kabupaten'     => 'MALUKU TENGGARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '8103','kd_provinsi'   => '81','kabupaten'     => 'MALUKU TENGAH','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '8104','kd_provinsi'   => '81','kabupaten'     => 'BURU','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '8105','kd_provinsi'   => '81','kabupaten'     => 'KEPULAUAN ARU','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '8106','kd_provinsi'   => '81','kabupaten'     => 'SERAM BAGIAN BARAT','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '8107','kd_provinsi'   => '81','kabupaten'     => 'SERAM BAGIAN TIMUR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '8108','kd_provinsi'   => '81','kabupaten'     => 'MALUKU BARAT DAYA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '8109','kd_provinsi'   => '81','kabupaten'     => 'BURU SELATAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '8171','kd_provinsi'   => '81','kabupaten'     => 'KOTA AMBON','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '8172','kd_provinsi'   => '81','kabupaten'     => 'KOTA TUAL','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '8201','kd_provinsi'   => '82','kabupaten'     => 'HALMAHERA BARAT','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '8202','kd_provinsi'   => '82','kabupaten'     => 'HALMAHERA TENGAH','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '8203','kd_provinsi'   => '82','kabupaten'     => 'KEPULAUAN SULA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '8204','kd_provinsi'   => '82','kabupaten'     => 'HALMAHERA SELATAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '8205','kd_provinsi'   => '82','kabupaten'     => 'HALMAHERA UTARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '8206','kd_provinsi'   => '82','kabupaten'     => 'HALMAHERA TIMUR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '8207','kd_provinsi'   => '82','kabupaten'     => 'PULAU MOROTAI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '8271','kd_provinsi'   => '82','kabupaten'     => 'KOTA TERNATE','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '8272','kd_provinsi'   => '82','kabupaten'     => 'KOTA TIDORE KEPULAUAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9101','kd_provinsi'   => '91','kabupaten'     => 'FAKFAK','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9102','kd_provinsi'   => '91','kabupaten'     => 'KAIMANA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9103','kd_provinsi'   => '91','kabupaten'     => 'TELUK WONDAMA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9104','kd_provinsi'   => '91','kabupaten'     => 'TELUK BINTUNI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9105','kd_provinsi'   => '91','kabupaten'     => 'MANOKWARI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9106','kd_provinsi'   => '91','kabupaten'     => 'SORONG SELATAN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9107','kd_provinsi'   => '91','kabupaten'     => 'SORONG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9108','kd_provinsi'   => '91','kabupaten'     => 'RAJA AMPAT','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9109','kd_provinsi'   => '91','kabupaten'     => 'TAMBRAUW','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9171','kd_provinsi'   => '91','kabupaten'     => 'KOTA SORONG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9401','kd_provinsi'   => '94','kabupaten'     => 'MERAUKE','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9402','kd_provinsi'   => '94','kabupaten'     => 'JAYAWIJAYA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9403','kd_provinsi'   => '94','kabupaten'     => 'JAYAPURA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9404','kd_provinsi'   => '94','kabupaten'     => 'NABIRE','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9408','kd_provinsi'   => '94','kabupaten'     => 'KEPULAUAN YAPEN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9409','kd_provinsi'   => '94','kabupaten'     => 'BIAK NUMFOR','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9410','kd_provinsi'   => '94','kabupaten'     => 'PANIAI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9411','kd_provinsi'   => '94','kabupaten'     => 'PUNCAK JAYA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9412','kd_provinsi'   => '94','kabupaten'     => 'MIMIKA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9413','kd_provinsi'   => '94','kabupaten'     => 'BOVEN DIGOEL','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9414','kd_provinsi'   => '94','kabupaten'     => 'MAPPI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9415','kd_provinsi'   => '94','kabupaten'     => 'ASMAT','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9416','kd_provinsi'   => '94','kabupaten'     => 'YAHUKIMO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9417','kd_provinsi'   => '94','kabupaten'     => 'PEGUNUNGAN BINTANG','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9418','kd_provinsi'   => '94','kabupaten'     => 'TOLIKARA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9419','kd_provinsi'   => '94','kabupaten'     => 'SARMI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9420','kd_provinsi'   => '94','kabupaten'     => 'KEEROM','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9426','kd_provinsi'   => '94','kabupaten'     => 'WAROPEN','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9427','kd_provinsi'   => '94','kabupaten'     => 'SUPIORI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9428','kd_provinsi'   => '94','kabupaten'     => 'MAMBERAMO RAYA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9429','kd_provinsi'   => '94','kabupaten'     => 'NDUGA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9430','kd_provinsi'   => '94','kabupaten'     => 'LANNY JAYA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9431','kd_provinsi'   => '94','kabupaten'     => 'MAMBERAMO TENGAH','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9432','kd_provinsi'   => '94','kabupaten'     => 'YALIMO','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9433','kd_provinsi'   => '94','kabupaten'     => 'PUNCAK','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9434','kd_provinsi'   => '94','kabupaten'     => 'DOGIYAI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9435','kd_provinsi'   => '94','kabupaten'     => 'INTAN JAYA','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9436','kd_provinsi'   => '94','kabupaten'     => 'DEIYAI','created_at'    => Carbon::now()],
            ['kd_kabupaten'  => '9471','kd_provinsi'   => '94','kabupaten'     => 'KOTA JAYAPURA','created_at'    => Carbon::now()],
            /* ['kd_provinsi'   => '11',  'kd_kabupaten'  => '11','kabupaten'     =>'ACEH','created_at'    => Carbon::now()] */
        
        ];
        MstKabupaten::insert($kabupatens);
    }
}
